feign:
  compression:
    request:
      enabled: true
      min-request-size: 512
    response:
      enabled: true
      mime-types: text/xml,application/xml,application/json
    client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 60000