CREATE TABLE `city_info`(
    `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` varchar(50) NOT NULL,
    `province` varchar(50) NOT NULL,
    `level` varchar(50) NOT NULL,
);

INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shanghai', 'Shanghai  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Beijing', 'Beijing  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shenzhen', 'Guangdong  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Chongqing', 'Chongqing  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Guangzhou', 'Guangdong  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Chengdu', 'Sichuan  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Tianjin', 'Tianjin  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Wuhan', 'Hubei  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Dongguan', 'Guangdong  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xi\'an', 'Shaanxi  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Hangzhou', 'Zhejiang  ', 'megaCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Foshan', 'Guangdong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nanjing', 'Jiangsu  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shenyang', 'Liaoning  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Qingdao', 'Shandong  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jinan', 'Shandong  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changsha', 'Hunan  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Harbin', 'Heilongjiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhengzhou', 'Henan  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Kunming', 'Yunnan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Dalian', 'Liaoning  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nanning', 'Guangxi', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shijiazhuang', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xiamen', 'Fujian  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Taiyuan', 'Shanxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Suzhou', 'Jiangsu  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Guiyang', 'Guizhou  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Hefei', 'Anhui  ', 'majorCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Urumqi', 'Xinjiang', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Ningbo', 'Zhejiang', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Wuxi', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Fuzhou', 'Fujian  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changchun', 'Jilin  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nanchang', 'Jiangxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changzhou', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Lanzhou', 'Gansu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhongshan', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Huizhou', 'Guangdong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shantou', 'Guangdong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Linyi', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zibo', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Wenzhou', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Hohhot', 'Inner Mongolia', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shaoxing', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Tangshan', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Haikou', 'Hainan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Liuzhou', 'Guangxi', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xuzhou', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yantai', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Luoyang', 'Henan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Handan', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhuhai', 'Guangdong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Baotou', 'Inner Mongolia', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Baoding', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Weifang', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Datong', 'Shanxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jiangmen', 'Guangdong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Ganzhou', 'Jiangxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xining', 'Qinghai  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nantong', 'Jiangsu', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yinchuan', 'Ningxia', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yangzhou', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zunyi', 'Guizhou  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xiangyang', 'Hubei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Anshan', 'Liaoning  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Kunshan', 'Jiangsu  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Putian', 'Fujian  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Mianyang', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yancheng', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Quanzhou', 'Fujian  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xianyang', 'Shaanxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Taizhou', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Wuhu', 'Anhui  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhuzhou', 'Hunan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Huaian', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jining', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jilin', 'Jilin  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Daqing', 'Heilongjiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Guilin', 'Guangxi', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Qinhuangdao', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhanjiang', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yichang', 'Hubei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Qiqihar', 'Heilongjiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Fushun', 'Liaoning  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shangrao', 'Jiangxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nanchong', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yiwu', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xingtai', 'Hebei  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Taian', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Kaifeng', 'Henan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhangjiakou', 'Hebei  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xinxiang', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Liaocheng', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Huainan', 'Anhui  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shiyan', 'Hubei  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yibin', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zaozhuang', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yueyang', 'Hunan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Cixi', 'Zhejiang  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Hengyang', 'Hunan', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changzhi', 'Shanxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Lianyungang', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jinzhou', 'Liaoning  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Chifeng', 'Inner Mongolia', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Luzhou', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Anyang', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Pingdingshan', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jiaxing', 'Zhejiang  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Ruian', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Taizhou', 'Jiangsu  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Qujing', 'Yunnan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Dazhou', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yingkou', 'Liaoning  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jieyang', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Panjin', 'Liaoning  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Chaozhou', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Dongying', 'Shandong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Maoming', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changde', 'Hunan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jiujiang', 'Jiangxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Qingyuan', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xinyang', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yueqing', 'Zhejiang  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Ma\'anshan', 'Anhui  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Fuyang', 'Anhui  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Rizhao', 'Shandong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Baoji', 'Shaanxi  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Nanyang', 'Henan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Hengshui', 'Hebei  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhaoqing', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Changshu', 'Jiangsu  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Suqian', 'Jiangsu  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yulin', 'Shaanxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jingzhou', 'Hubei  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Xuchang', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Lu\'an', 'Anhui  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Heze', 'Shandong  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Huaibei', 'Anhui  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Cangzhou', 'Hebei  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jinhua', 'Zhejiang  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhenjiang', 'Jiangsu  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jinzhong', 'Shanxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Fuzhou', 'Jiangxi  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Jiaozuo', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Chenzhou', 'Hunan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zigong', 'Sichuan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Benxi', 'Liaoning  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhangzhou', 'Fujian  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Shangqiu', 'Henan  ', 'bigCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Zhoukou', 'Henan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Suining', 'Sichuan  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Huzhou', 'Zhejiang  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Yangjiang', 'Guangdong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Binzhou', 'Shandong  ', 'mediunCity');
INSERT INTO `city_info` (`name`, `province`, `level`) VALUES ('Liaoyang', 'Liaoning', 'mediunCity');

