CREATE TABLE city (
                      id INT AUTO_INCREMENT PRIMARY KEY,
                      city_name VARCHAR(255) NOT NULL,
                      province_name VARCHAR(255) NOT NULL
);

INSERT INTO city (city_name, province_name) VALUES
                                                ('Shijiazhuang', 'Hebei'),
                                                ('Tangshan', 'Hebei'),
                                                ('Qinhuangdao', 'Hebei'),
                                                ('Handan', 'Hebei'),
                                                ('Xingtai', 'Hebei'),
                                                ('Baoding', 'Hebei'),
                                                ('Zhangjiakou', 'Hebei'),
                                                ('Chengde', 'Hebei'),
                                                ('Cangzhou', 'Hebei'),
                                                ('Langfang', 'Hebei'),
                                                ('Hengshui', 'Hebei'),

                                                ('Taiyuan', 'Shanxi'),
                                                ('Datong', 'Shanxi'),
                                                ('Yangquan', 'Shanxi'),
                                                ('Changzhi', 'Shanxi'),
                                                ('Jincheng', 'Shanxi'),
                                                ('Shuozhou', 'Shanxi'),
                                                ('Jinzhong', 'Shanxi'),
                                                ('Yuncheng', 'Shanxi'),
                                                ('Xinzhou', 'Shanxi'),
                                                ('Linfen', 'Shanxi'),
                                                ('Lüliang', 'Shanxi'),

                                                ('Hohhot', 'Inner Mongolia'),
                                                ('Baotou', 'Inner Mongolia'),
                                                ('Wuhai', 'Inner Mongolia'),
                                                ('Chifeng', 'Inner Mongolia'),
                                                ('Tongliao', 'Inner Mongolia'),
                                                ('Ordos', 'Inner Mongolia'),
                                                ('Hulunbuir', 'Inner Mongolia'),
                                                ('Bayannur', 'Inner Mongolia'),
                                                ('Ulanqab', 'Inner Mongolia'),

                                                ('Shenyang', 'Liaoning'),
                                                ('Dalian', 'Liaoning'),
                                                ('Anshan', 'Liaoning'),
                                                ('Fushun', 'Liaoning'),
                                                ('Benxi', 'Liaoning'),
                                                ('Dandong', 'Liaoning'),
                                                ('Jinzhou', 'Liaoning'),
                                                ('Yingkou', 'Liaoning'),
                                                ('Fuxin', 'Liaoning'),
                                                ('Liaoyang', 'Liaoning'),
                                                ('Panjin', 'Liaoning'),
                                                ('Tieling', 'Liaoning'),
                                                ('Chaoyang', 'Liaoning'),
                                                ('Huludao', 'Liaoning'),

                                                ('Changchun', 'Jilin'),
                                                ('Jilin', 'Jilin'),
                                                ('Siping', 'Jilin'),
                                                ('Liaoyuan', 'Jilin'),
                                                ('Tonghua', 'Jilin'),
                                                ('Baishan', 'Jilin'),
                                                ('Songyuan', 'Jilin'),
                                                ('Baicheng', 'Jilin'),

                                                ('Harbin', 'Heilongjiang'),
                                                ('Qiqihar', 'Heilongjiang'),
                                                ('Jixi', 'Heilongjiang'),
                                                ('Hegang', 'Heilongjiang'),
                                                ('Shuangyashan', 'Heilongjiang'),
                                                ('Daqing', 'Heilongjiang'),
                                                ('Yichun', 'Heilongjiang'),
                                                ('Jiamusi', 'Heilongjiang'),
                                                ('Qitaihe', 'Heilongjiang'),
                                                ('Mudanjiang', 'Heilongjiang'),
                                                ('Heihe', 'Heilongjiang'),
                                                ('Suihua', 'Heilongjiang'),

                                                ('Nanjing', 'Jiangsu'),
                                                ('Wuxi', 'Jiangsu'),
                                                ('Xuzhou', 'Jiangsu'),
                                                ('Changzhou', 'Jiangsu'),
                                                ('Suzhou', 'Jiangsu'),
                                                ('Nantong', 'Jiangsu'),
                                                ('Lianyungang', 'Jiangsu'),
                                                ('Huaian', 'Jiangsu'),
                                                ('Yancheng', 'Jiangsu'),
                                                ('Yangzhou', 'Jiangsu'),
                                                ('Zhenjiang', 'Jiangsu'),
                                                ('Taizhou', 'Jiangsu'),
                                                ('Suqian', 'Jiangsu'),

                                                ('Hangzhou', 'Zhejiang'),
                                                ('Ningbo', 'Zhejiang'),
                                                ('Wenzhou', 'Zhejiang'),
                                                ('Jiaxing', 'Zhejiang'),
                                                ('Huzhou', 'Zhejiang'),
                                                ('Shaoxing', 'Zhejiang'),
                                                ('Jinhua', 'Zhejiang'),
                                                ('Quzhou', 'Zhejiang'),
                                                ('Zhoushan', 'Zhejiang'),
                                                ('Taizhou', 'Zhejiang'),
                                                ('Lishui', 'Zhejiang'),

                                                ('Hefei', 'Anhui'),
                                                ('Wuhu', 'Anhui'),
                                                ('Bengbu', 'Anhui'),
                                                ('Huainan', 'Anhui'),
                                                ('Maanshan', 'Anhui'),
                                                ('Huaibei', 'Anhui'),
                                                ('Tongling', 'Anhui'),
                                                ('Anqing', 'Anhui'),
                                                ('Huangshan', 'Anhui'),
                                                ('Chuzhou', 'Anhui'),
                                                ('Fuyang', 'Anhui'),
                                                ('Suzhou', 'Anhui'),
                                                ('Lu''an', 'Anhui'),
                                                ('Bozhou', 'Anhui'),
                                                ('Chizhou', 'Anhui'),
                                                ('Xuancheng', 'Anhui'),

                                                ('Fuzhou', 'Fujian'),
                                                ('Xiamen', 'Fujian'),
                                                ('Sanming', 'Fujian'),
                                                ('Putian', 'Fujian'),
                                                ('Quanzhou', 'Fujian'),
                                                ('Zhangzhou', 'Fujian'),
                                                ('Nanping', 'Fujian'),
                                                ('Longyan', 'Fujian'),
                                                ('Ningde', 'Fujian'),

                                                ('Nanchang', 'Jiangxi'),
                                                ('Jingdezhen', 'Jiangxi'),
                                                ('Pingxiang', 'Jiangxi'),
                                                ('Jiujiang', 'Jiangxi'),
                                                ('Xinyu', 'Jiangxi'),
                                                ('Yingtan', 'Jiangxi'),
                                                ('Ganzhou', 'Jiangxi'),
                                                ('Ji''an', 'Jiangxi'),
                                                ('Yichun', 'Jiangxi'),
                                                ('Fuzhou', 'Jiangxi'),
                                                ('Shangrao', 'Jiangxi'),

                                                ('Jinan', 'Shandong'),
                                                ('Qingdao', 'Shandong'),
                                                ('Zibo', 'Shandong'),
                                                ('Zaozhuang', 'Shandong'),
                                                ('Dongying', 'Shandong'),
                                                ('Yantai', 'Shandong'),
                                                ('Weifang', 'Shandong'),
                                                ('Jining', 'Shandong'),
                                                ('Taian', 'Shandong'),
                                                ('Weihai', 'Shandong'),
                                                ('Rizhao', 'Shandong'),
                                                ('Linyi', 'Shandong'),
                                                ('Dezhou', 'Shandong'),
                                                ('Liaocheng', 'Shandong'),
                                                ('Binzhou', 'Shandong'),
                                                ('Heze', 'Shandong'),

                                                ('Zhengzhou', 'Henan'),
                                                ('Kaifeng', 'Henan'),
                                                ('Luoyang', 'Henan'),
                                                ('Pingdingshan', 'Henan'),
                                                ('Anyang', 'Henan'),
                                                ('Hebi', 'Henan'),
                                                ('Xinxiang', 'Henan'),
                                                ("yang", 'Henan'),
                                                ('Xinxiang', 'Henan'),
                                                ('Jiaozuo', 'Henan'),
                                                ('Puyang', 'Henan'),
                                                ('Xuchang', 'Henan'),
                                                ('Luohe', 'Henan'),
                                                ('Sanmenxia', 'Henan'),
                                                ('Nanyang', 'Henan'),
                                                ('Shangqiu', 'Henan'),
                                                ('Xinyang', 'Henan'),
                                                ('Zhoukou', 'Henan'),
                                                ('Zhumadian', 'Henan'),

                                                ('Wuhan', 'Hubei'),
                                                ('Huangshi', 'Hubei'),
                                                ('Shiyan', 'Hubei'),
                                                ('Yichang', 'Hubei'),
                                                ('Xiangyang', 'Hubei'),
                                                ('Ezhou', 'Hubei'),
                                                ('Jingmen', 'Hubei'),
                                                ('Xiaogan', 'Hubei'),
                                                ('Jingzhou', 'Hubei'),
                                                ('Huanggang', 'Hubei'),
                                                ('Xianning', 'Hubei'),
                                                ('Suizhou', 'Hubei'),

                                                ('Changsha', 'Hunan'),
                                                ('Zhuzhou', 'Hunan'),
                                                ('Xiangtan', 'Hunan'),
                                                ('Hengyang', 'Hunan'),
                                                ('Shaoyang', 'Hunan'),
                                                ('Yueyang', 'Hunan'),
                                                ('Changde', 'Hunan'),
                                                ('Zhangjiajie', 'Hunan'),
                                                ('Yiyang', 'Hunan'),
                                                ('Chenzhou', 'Hunan'),
                                                ('Yongzhou', 'Hunan'),
                                                ('Huaihua', 'Hunan'),
                                                ('Loudi', 'Hunan'),

                                                ('Guangzhou', 'Guangdong'),
                                                ('Shaoguan', 'Guangdong'),
                                                ('Shenzhen', 'Guangdong'),
                                                ('Zhuhai', 'Guangdong'),
                                                ('Shantou', 'Guangdong'),
                                                ('Foshan', 'Guangdong'),
                                                ('Jiangmen', 'Guangdong'),
                                                ('Zhanjiang', 'Guangdong'),
                                                ('Maoming', 'Guangdong'),
                                                ('Zhaoqing', 'Guangdong'),
                                                ('Huizhou', 'Guangdong'),
                                                ('Meizhou', 'Guangdong'),
                                                ('Shanwei', 'Guangdong'),
                                                ('Heyuan', 'Guangdong'),
                                                ('Yangjiang', 'Guangdong'),
                                                ('Qingyuan', 'Guangdong'),
                                                ('Dongguan', 'Guangdong'),
                                                ('Zhongshan', 'Guangdong'),
                                                ('Chaozhou', 'Guangdong'),
                                                ('Jieyang', 'Guangdong'),
                                                ('Yunfu', 'Guangdong'),

                                                ('Nanning', 'Guangxi'),
                                                ('Liuzhou', 'Guangxi'),
                                                ('Guilin', 'Guangxi'),
                                                ('Wuzhou', 'Guangxi'),
                                                ('Beihai', 'Guangxi'),
                                                ('Fangchenggang', 'Guangxi'),
                                                ('Qinzhou', 'Guangxi'),
                                                ('Guigang', 'Guangxi'),
                                                ('Yulin', 'Guangxi'),
                                                ('Baise', 'Guangxi'),
                                                ('Hezhou', 'Guangxi'),
                                                ('Hechi', 'Guangxi'),
                                                ('Laibin', 'Guangxi'),

                                                ('Haikou', 'Hainan'),
                                                ('Sanya', 'Hainan'),
                                                ('Sansha', 'Hainan'),
                                                ('Danzhou', 'Hainan'),

                                                ('Chengdu', 'Sichuan'),
                                                ('Zigong', 'Sichuan'),
                                                ('Panzhihua', 'Sichuan'),
                                                ('Luzhou', 'Sichuan'),
                                                ('Deyang', 'Sichuan'),
                                                ('Mianyang', 'Sichuan'),
                                                ('Guangyuan', 'Sichuan'),
                                                ('Suining', 'Sichuan'),
                                                ('Neijiang', 'Sichuan'),
                                                ('Leshan', 'Sichuan'),
                                                ('Nanchong', 'Sichuan'),
                                                ('Meishan', 'Sichuan'),
                                                ('Yibin', 'Sichuan'),
                                                ('Guang''an', 'Sichuan'),
                                                ('Dazhou', 'Sichuan'),
                                                ('Ya''an', 'Sichuan'),
                                                ('Bazhong', 'Sichuan'),
                                                ('Ziyang', 'Sichuan'),

                                                ('Guiyang', 'Guizhou'),
                                                ('Liupanshui', 'Guizhou'),
                                                ('Zunyi', 'Guizhou'),
                                                ('Anshun', 'Guizhou'),
                                                ('Bijie', 'Guizhou'),
                                                ('Tongren', 'Guizhou'),

                                                ('Kunming', 'Yunnan'),
                                                ('Qujing', 'Yunnan'),
                                                ('Yuxi', 'Yunnan'),
                                                ('Baoshan', 'Yunnan'),
                                                ('Zhaotong', 'Yunnan'),
                                                ('Lijiang', 'Yunnan'),
                                                ('Puer', 'Yunnan'),
                                                ('Lincang', 'Yunnan'),

                                                ('Lhasa', 'Tibet'),
                                                ('Rikaze', 'Tibet'),
                                                ('Qamdo', 'Tibet'),
                                                ('Nyingchi', 'Tibet'),
                                                ('Shannan', 'Tibet'),
                                                ('Nagqu', 'Tibet'),

                                                ('Xining', 'Qinghai'),
                                                ('Haidong', 'Qinghai'),

                                                ('Yinchuan', 'Ningxia'),
                                                ('Shizuishan', 'Ningxia'),
                                                ('Wuzhong', 'Ningxia'),
                                                ('Guyuan', 'Ningxia'),
                                                ('Zhongwei', 'Ningxia'),

                                                ('Urumqi', 'Xinjiang'),
                                                ('Karamay', 'Xinjiang'),
                                                ('Turpan', 'Xinjiang'),
                                                ('Hami', 'Xinjiang'),

                                                ('Taipei', 'Taiwan'),
                                                ('Kaohsiung', 'Taiwan'),
                                                ('Tainan', 'Taiwan'),
                                                ('New Taipei', 'Taiwan'),
                                                ('Taoyuan', 'Taiwan'),
                                                ('Taichung', 'Taiwan');
