server:
  port: 7000
spring:
  profiles:
    active: dev
  application:
    name: system-gateway
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://localhost:3306/NEUSoftPractice_public?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: route_administrator
#          uri: lb://system-TaskManage
#          predicates:
#            - Path=/api/task/**
#        - id: route_gridDetector
#          uri: lb://system-ReportManage
#          predicates:
#            - Path=/api/report/**
#        - id : route_supervisor
#          uri: lb://system-SubmissionManage
#          predicates:
#            - Path=/api/submission/**
#        - id : route_task
#          uri: lb://system-TaskManage
#          predicates:
#            - Path=/api/task/**
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000ms
  freemarker:
    prefer-file-system-access:
