server:
  port: 8080
  additionalPorts: 8081,8082,8083,8084,8085,8086
spring:
  main:
    web-application-type: reactive
  application:
    name: system-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/NEUSoftPractice_service?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      filters:
        global:
         - com.neusoft.springcloud.gateway.filter.AuthGatewayFilterFactory
      routes:
        - id: system-AirDataManage
          uri: lb://system-AirDataManage
          order: 1
          predicates:
            - Path=/airData/**

        - id: system-PermissionControl_user
          uri: lb://system-PermissionControl
          order: 1
          predicates:
            - Path=/user/**

        - id: system-PermissionControl_administrator
          uri: lb://system-PermissionControl
          order: 1
          predicates:
            - Path=/administrator/**

        - id: system-PermissionControl_gridDetector
          uri: lb://system-PermissionControl
          order: 1
          predicates:
            - Path=/gridDetector/**

        - id: system-PermissionControl_supervisor
          uri: lb://system-PermissionControl
          order: 1
          predicates:
            - Path=/supervisor/**

        - id: system-ReportManage
          uri: lb://system-ReportManage
          order: 1
          predicates:
            - Path=/report/**

        - id: system-SubmissionManage
          uri: lb://system-SubmissionManage
          order: 1
          predicates:
            - Path=/submission/**

        - id: system-TaskManage
          uri: lb://system-TaskManage
          order: 1
          predicates:
            - Path=/task/**

        - id: system-ZoneManage
          uri: lb://system-ZoneManage
          order: 1
          predicates:
            - Path=/city/**
  data:
    redis:
      database: 0
      host: localhost
      port: 6379