server:
  port: 8081

spring:
  application:
    name: system-PermissionControl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/NEUSoftPractice_public?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 50MB
      max-request-size: 50MB
      location: /tmp/upload
  data:
    redis:
      database: 0
redis:
  host: localhost
  port: 6379
  maxIdle: 300
  maxTotal: 600
  maxWait: 1000
  testOnBorrow: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
